version: '3'

services:
  app :
    build: ./app/
  db:
    container_name: pg_container
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432
